### ISSUE TITLE
Installation fails: cannot download snapshot

### ISSUE THREAD

**Issue by PascalLeMerrer** [gradle/gradle-script-kotlin#100]
Hello

I'm trying to follow the setup process for the hello world sample.
I installed the last version of Intellij idea CE, downloaded and installed kotlin-plugin-1.1-M01.zip.
Importing the gradle hello world sample fails with a "resolve error" message.

![capture d ecran 2016-07-16 a 16 43 46](https://cloud.githubusercontent.com/assets/873398/16895406/6f16f1bc-4b75-11e6-8188-4afca7e6149d.png)

**Comment by bamboo** [comment]
Please try again with the latest version.

**Comment by bamboo** [comment]
It might have been a hiccup in the server hosting our distributions, please try again against the latest version of the repository. 

Remember NOT to accept IDEA's suggestion of using a different distribution.

**Comment by PascalLeMerrer** [comment]
it works now. Thx.
