### ISSUE TITLE
Speed up IDEA classpath computation

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#102]
By only retrieving the model when there are changes to the `buildscript` block between requests.

**Comment by ligee** [comment]
Just would like to mention that I implemented that one among changes I'm preparing now.

**Comment by bamboo** [comment]
Great to hear, @ligee. Looking forward to try them out.

**Comment by bamboo** [comment]
One thing we should keep in mind is that this approach will yield false negatives when the Kotlin build script is not the main Gradle build file as it is the case right now with gradle-script-kotlin itself.

In that case, the buildscript classpath will be controlled by `build.gradle`.

And to complicate matters further there's always the chance that some out of band mechanism could be influencing the classpath as well, for instance a project property maintained in `gradle.properties` or [some other external file that is read within the buildscript block](https://github.com/gradle/gradle-script-kotlin/blob/master/kotlin-version.txt).

**Comment by ligee** [comment]
Yep, that's understood. Actually this implementation is more like initial point, it is clear that we should take more complicated model into account.
I was thinking about possible solutions, but I haven't found a good one yet. 
The relatively simple one would be to keep track of all dependencies' dependencies in the `DepsWithBuldscriptSectionHash` and check whether they are changed as well.

**Comment by bamboo** [comment]
Resolved in 7a6bd9d4fcf1c31adb08bea5e1a33efbb3267a0d. Superceded by #110.
