### ISSUE TITLE
distribution url leads to file not found exception

### ISSUE THREAD

**Issue by amb-it-ion** [gradle/gradle-script-kotlin#105]
when running gradlew.bat from the samples/modularity folder, I get:

gradlew.bat
Downloading https://services.gradle.org/distributions-snapshots/gradle-script-kotlin-3.0.0-20160719234019+0000-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle.org/distributions-snapshots/gradle-script-kotlin-3.0.0-20160719234019+0000-bin.zip (...)

**Comment by amb-it-ion** [comment]
This might have to do with me trying to auto-import the module into intellij 2016.2, which apparently modified the distribution url?

**Comment by amb-it-ion** [comment]
gradlew.bat wrapper --gradle-distribution-url https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.0.0-20160719234019+0000-bin.zip
Downloading https://services.gradle.org/distributions-snapshots/gradle-3.0.0-20160719234019+0000-bin.zip

Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle.org/distributions-snapshots/gradle-3.0.0-20160719234019+0000-bin.zip

**Comment by amb-it-ion** [comment]
not sure what, but something is changing my gradle-wrapper.properties

**Comment by amb-it-ion** [comment]
Ok I give up, no idea how to get this to work in the IDE. Buildings works fine though, but that I can do with groovy as well... it was the IDE support that got me excited.

**Comment by bamboo** [comment]
Please try again against the latest version.
