### ISSUE TITLE
Can't navigate to source in build.gradle.kts in sample applications

### ISSUE THREAD

**Issue by hayohayo** [gradle/gradle-script-kotlin#109]
I'm trying to follow this instruction: https://github.com/gradle/gradle-script-kotlin/tree/master/samples.

I have opened hello-word in IntelliJ IDEA 2016.2.1 (Mac), syntax highlighting works in `build.gradle.kts`, autocomplete also works (my Kotlin plugin version is Version: 1.0.3-release-IJ2016.1-120). However every time I'm trying to go to declaration of any symbol in the file, I get "Cannot find declaration to go to".  I don't see any documentation either.

**Comment by bamboo** [comment]
Hi @hayohayo, Kotlin 1.0.3 is not supported. You'll need at least 1.1-M01 from the EAP channel.

**Comment by hayohayo** [comment]
Ah... totally missed that part. Thank you @bamboo!
