### ISSUE TITLE
Class loader issue when applying a Gradle plugin

### ISSUE THREAD

**Issue by RobWin** [gradle/gradle-script-kotlin#119]
Hi,

I'm have applied a Gradle plugin (`com.netflix.nebula:gradle-ospackage-plugin`) to my `build.gradle.kts` and I get the following error now.

`Error:Cause: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/gradle/script/lang/kotlin/provider/PostDelegatingClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature`

Not sure if its a problem of `gradle-script-kotlin`.

I'm using Gradle 3.0 and the IntelliJ Communit Edition with Kotlin Plugin 1.1-M01

**Comment by amb-it-ion** [comment]
same here. effectively stops me from using it in anything other than reviewing the sample code.

**Comment by RobWin** [comment]
Yes
