### ISSUE TITLE
Consider automatically extracting javadoc from the Gradle API and converting it to KDoc

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#120]
[JavaParser](http://javaparser.org/) might be a good option.

**Comment by yole** [comment]
Why exactly do you need that? Dokka can parse Javadoc in Java code and generate Kotlin documentation from it.

**Comment by bamboo** [comment]
@yole gradle-script-kotlin currently generates extension members for the Gradle API so `Action<T>` parameters are treated as `T.() -> Unit` (see #117). We want those extensions to sort of _inherit_ the documentation of the members they were generated from so the docs are immediately accessible in the IDE without any indirections. 

Could Dokka  be used to programatically extract KDoc from the Gradle Java source files?

**Comment by yole** [comment]
If you need to see docs in the IDE, it's possible to write a custom extension in the plugin that would show them. This should be far easier than building a separate tool to extract and convert the docs.

**Comment by bamboo** [comment]
@yole, _far easier_ sounds great! If I understood you correctly this would be like writing a plugin to the IDEA Kotlin plugin? Could you share any pointers on that?

**Comment by bamboo** [comment]
Superseded by #155. Extension members will not be needed.
