### ISSUE TITLE
Add missing `Action<T>` overloads to `org.gradle.api.Project`

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#122]
The following methods are missing a `Action<T>` or `Spec<T>` counterpart:

```
org.gradle.api.Project#task(java.util.Map, java.lang.String, groovy.lang.Closure)
org.gradle.api.Project#task(java.lang.String, groovy.lang.Closure)
org.gradle.api.Project#project(java.lang.String, groovy.lang.Closure)
org.gradle.api.Project#files(java.lang.Object, groovy.lang.Closure)
org.gradle.api.Project#fileTree(java.lang.Object, groovy.lang.Closure)
org.gradle.api.Project#ant(groovy.lang.Closure)
org.gradle.api.Project#configurations(groovy.lang.Closure)
org.gradle.api.Project#artifacts(groovy.lang.Closure)
org.gradle.api.Project#repositories(groovy.lang.Closure)
org.gradle.api.Project#dependencies(groovy.lang.Closure)
org.gradle.api.Project#buildscript(groovy.lang.Closure)
org.gradle.api.Project#container(java.lang.Class, groovy.lang.Closure)
```

**Comment by eskatos** [comment]
`org.gradle.api.Project#container(java.lang.Class, groovy.lang.Closure)` already has a strongly typed counterpart `org.gradle.api.Project#container(java.lang.Class<T>, org.gradle.api.NamedDomainObjectFactory<T>)`

**Comment by eskatos** [comment]
@bamboo I reverted the change because it was causing a failure I'd like to discuss with you when you get back, see https://builds.gradle.org/viewLog.html?buildId=1672517

**Comment by bamboo** [comment]
Right. We need to wait until gradle/gradle-script-kotlin#155 is implemented.

**Comment by eskatos** [comment]
Okay, I'll move this issue back in backlog then.

**Comment by eskatos** [comment]
A first PR against Gradle adds overloads for all methods but `repositories()` and `dependencies()`: https://github.com/gradle/gradle/pull/1284

For those two methods we have to wait for the `@HasImplicitReceiver` annotation to take effect as they would break the version of gradle-script-kotlin included in Gradle.

Changes to add those two overloads are in a separate branch:
https://github.com/gradle/gradle/tree/pm-action-overloads-project-step2

**Comment by eskatos** [comment]
Removed the overload of `Project#configure(Closure, Object)` in `master`. That one too needs to wait.

Added on top of the `pm-action-overloads-project-missing` branch.

**Comment by bamboo** [comment]
Remaining work moved to #262.
