### ISSUE TITLE
Add missing `Action<T>` overloads to `org.gradle.api.tasks.*SourceSet`

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#124]
The following methods are missing a `Action<T>` or `Spec<T>` counterpart:

```
org.gradle.api.tasks.GroovySourceSet#groovy(groovy.lang.Closure)
org.gradle.api.tasks.ScalaSourceSet#scala(groovy.lang.Closure)
org.gradle.api.tasks.SourceSet#resources(groovy.lang.Closure)
org.gradle.api.tasks.SourceSet#java(groovy.lang.Closure)
```

**Comment by eskatos** [comment]
Changes pushed to https://github.com/gradle/gradle/commits/pm-sourceset-overloads
Waiting for CI to validate before opening a PR against `gradle/gradle` for review

**Comment by eskatos** [comment]
@bamboo, looking at `JavaPluginConvention#sourceSets(Closure)`, in the context of this issue, it seems it's a Groovy DSL only method just like [NamedDomainObjectContainer#configure](https://github.com/gradle/gradle-script-kotlin/issues/125#issuecomment-257641657) and that there’s no need for an `Action<T>` based overload, correct?

**Comment by eskatos** [comment]
See https://gradle.slack.com/archives/gradle-script-kotlin/p1478721534000049

`JavaPluginConvention#sourceSets(Closure)` left untouched. We need a nice kotlin way to configure domain object collections for that.

**Comment by eskatos** [comment]
See #35 about domain object collections support

**Comment by eskatos** [comment]
@bamboo the PR for review: https://github.com/gradle/gradle/pull/838
