### ISSUE TITLE
Add missing `Action<T>` overloads to domain object collections

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#125]
The following methods are missing a `Action<T>` or `Spec<T>` counterpart:

```
org.gradle.api.DomainObjectCollection#findAll(groovy.lang.Closure)

org.gradle.api.DomainObjectSet#findAll(groovy.lang.Closure)

org.gradle.api.ExtensiblePolymorphicDomainObjectContainer#registerFactory(java.lang.Class, groovy.lang.Closure)

org.gradle.api.NamedDomainObjectCollection#getByName(java.lang.String, groovy.lang.Closure)
org.gradle.api.NamedDomainObjectCollection#addRule(java.lang.String, groovy.lang.Closure)

org.gradle.api.NamedDomainObjectContainer#configure(groovy.lang.Closure)

org.gradle.api.NamedDomainObjectList#findAll(groovy.lang.Closure)

org.gradle.api.NamedDomainObjectSet#findAll(groovy.lang.Closure)
```

**Comment by eskatos** [comment]
`org.gradle.api.ExtensiblePolymorphicDomainObjectContainer#registerFactory(java.lang.Class<U>, groovy.lang.Closure<? extends U>)` already has a strongly typed counterpart: `org.gradle.api.ExtensiblePolymorphicDomainObjectContainer#registerFactory(java.lang.Class<U>, org.gradle.api.NamedDomainObjectFactory<? extends U>)`

`org.gradle.api.NamedDomainObjectCollection#getByName(java.lang.String, groovy.lang.Closure)` already as an `Action` based counterpart.

**Comment by bamboo** [comment]
`#findAll(Closure)` doesn't require an overload because it's there just to override the Groovy version. In Kotlin we already have the `#filter` extension.

**Comment by bamboo** [comment]
`#configure(Closure)` doesn't require an overload because it's a DSL method. We need to provide an equivalent feature on the gradle-script-kotlin side.

**Comment by eskatos** [comment]
LGTM 👍

**Comment by eskatos** [comment]
See #35 about support for creation/configuration in domain object collections
