### ISSUE TITLE
Add missing `Action<T>` overloads to `org.gradle.api.file`

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#126]
The following methods are missing a `Action<T>` or `Spec<T>` counterpart:

```
org.gradle.api.file.ContentFilterable#filter(groovy.lang.Closure)

org.gradle.api.file.CopyProcessingSpec#rename(groovy.lang.Closure)

org.gradle.api.file.CopySpec#rename(groovy.lang.Closure)
org.gradle.api.file.CopySpec#filter(groovy.lang.Closure)

org.gradle.api.file.FileTree#matching(groovy.lang.Closure)
org.gradle.api.file.FileTree#visit(groovy.lang.Closure)
```

**Comment by eskatos** [comment]
`org.gradle.api.file.ContentFilterable#filter(groovy.lang.Closure)` already has a strongly typed counterpart: `org.gradle.api.file.ContentFilterable#filter(org.gradle.api.Transformer<java.lang.String,java.lang.String>)`

`org.gradle.api.file.CopyProcessingSpec#rename(groovy.lang.Closure)` too: `org.gradle.api.file.CopyProcessingSpec#rename(org.gradle.api.Transformer<java.lang.String,java.lang.String>)`

And the same in `CopySpec` for `rename()` and `filter()`.

These can already be used from Kotlin, e.g.:

```
task<Copy>("someCopy") {
  from("some/path") {
    rename { name -> name.toUpperCase() }
  }
  // ...
}
```

**Comment by eskatos** [comment]
Changes pushed to https://github.com/gradle/gradle/commits/pm-filetree-overloads
Waiting for CI to validate before opening a PR against `gradle/gradle` for review

**Comment by eskatos** [comment]
@bamboo the PR for review: https://github.com/gradle/gradle/pull/837
