### ISSUE TITLE
Build script in sub-project of a multi-project build can be edited with the correct classpath

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#130]
Compute the classpath correctly for the current project in a multi-project build.

**Comment by eskatos** [comment]
When you open a subproject build script in IDEA, it uses the classpath of the root project's build script. This issue is about providing IDEA with the correct classpath for each build scripts of a multi-project build.

**Comment by bamboo** [comment]
This works fine when importing samples directly but I noticed some instability against gradle-script-kotlin itself. It seems related to the presence of the samples sub-directory (which contains a lot of build scripts).

Requires more investigation.
