### ISSUE TITLE
404 links

### ISSUE THREAD

**Issue by sergey-morenets** [gradle/gradle-script-kotlin#141]
Hi guys

The links on the main page all produce 404 error, for example https://github.com/gradle/gradle-script-kotlin/tree/master/hello-world

**Comment by bamboo** [comment]
Thanks, @sergey-morenets !

**Comment by cbeams** [comment]
I wonder if this was a change on GitHub's side. Pretty sure those links worked when we created them. Anyway, thanks again @sergey-morenets for pointing it out.
