### ISSUE TITLE
Compilation classpath of applied script does not include classpath of enclosing script

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#150]
When a Kotlin build script is applied from a main Groovy build script, its compilation classpath won't include the classpath of the main script thus the following will fail to compile even when the main buildscript classpath includes `kotlin-gradle-plugin`:

``` kotlin
tasks.withType<KotlinCompile> {
    kotlinOptions.noOptimize = false
}
```

**Comment by oehme** [comment]
This is intentional. A script plugin cannot include the classpath of the project it is being applied to. Script plugins must be self-contained, as they can be applied to any number of projects.

**Comment by oehme** [comment]
In fact, the opposite relationship will be true in the future: The project should see what the script plugin provides. This is part of the stable plugin DSL project.

**Comment by bamboo** [comment]
Superseded by #180.
