### ISSUE TITLE
KT-12848 Allow to turn the first parameter of a SAM-converted lambda into the receiver

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#156]
https://youtrack.jetbrains.com/issue/KT-12848#comment=27-1651435

**Comment by bamboo** [comment]
@ligee, please let us know when this makes into a dev build we can use for gradle-script-kotlin.

**Comment by mkobit** [comment]
FYI looks like this made it into [`1.0.6`](https://blog.jetbrains.com/kotlin/2016/12/kotlin-1-0-6-is-here/) so it is (possibly?) in `1.1-M04`?

**Comment by bamboo** [comment]
@mkobit I didn't see it mentioned in the release notes. Did I miss it?

**Comment by mkobit** [comment]
@bamboo I could be misunderstanding the issue, but it sounded like this could be achieved by using a compiler plugin to handle the codegen.

The `1.0.6` notes ([here](https://blog.jetbrains.com/kotlin/2016/12/kotlin-1-0-6-is-here/)) mention a couple compiler plugins like the **all-open** and **no-arg** plugins. I didn't see anything in the `1.1-M4` notes ([here](https://blog.jetbrains.com/kotlin/2016/12/kotlin-1-1-m04-is-here/)) so I wasn't sure if it made it into there yet.

**Comment by bamboo** [comment]
Yeah, it wasn't explicitly mentioned in the release notes but it's there: JetBrains/kotlin@cbef0250aaa9d25060b46dca95a41c73f7276ba9

**Comment by hansd** [comment]
Any updates on the slow script compile times?

**Comment by bamboo** [comment]
The embeddable compiler changes are in. The required changes to IDEA will come in #252.
