### ISSUE TITLE
Upgrade to Kotlin 1.1-M02

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#164]

**Comment by hotchemi** [comment]
Can I possibly tackle to this issue?

**Comment by bamboo** [comment]
Hi @hotchemi. Thanks for your interest on implementing this feature but it was already being worked on by @ligee. I'm sorry we haven't made this clear in the issue assignment before. We'll be more careful in the future.

**Comment by hotchemi** [comment]
@bamboo Sure! I'm just asking and thx for your polite answer:D
