### ISSUE TITLE
Outline User Guide

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#176]

**Comment by pledbrook** [comment]
Developing the outline in [this Google Doc](https://docs.google.com/document/d/14ILW8IzctBBaJt-YrLWC1tNagN7aEIXzU5YtcfBUFFE/edit#)

**Comment by cbeams** [comment]
@pledbrook, in case you haven't already noticed the epic for this work at #106, you'll want to read through the comments there and click subscribe on that issue to make sure you get notified as folks weigh in further.

@bamboo, you might want to update the naming of that epic to more precisely reflect what we're actually planning. As opposed to "Improve documentation", I'd call the epic "User Manual" (or "Create User Manual"), rename this issue to "Outline user manual", then follow it up with discrete tasks for each of the actions that will need to be carried out to complete the epic—each of which will likely involve different people—such as:
 - Write user manual (includes the review process, and this issue can be converted to a pull request as the draft comes together)
 - Design user manual layout (will involve @aweida and possibly myself)
 - Implement user manual layout (will involve someone familiar with what we've been doing CSS-wise in other similar efforts of late) 

Note that this approach leaves aside the publication of API documentation as a completely separate epic to be addressed on its own. It is influenced by the decisions made here, as we'll want to publish these side by side, e.g. at https://gradle.github.io/gradle-script-kotlin/X.Y.Z/user-manual/ and https://gradle.github.io/gradle-script-kotlin/X.Y.Z/api/—but the latter can still be addressed separately (and probably subsequently) to the user manual effort.

**Comment by pledbrook** [comment]
@bamboo I have created a basic outline [here](https://docs.google.com/document/d/14ILW8IzctBBaJt-YrLWC1tNagN7aEIXzU5YtcfBUFFE/edit#heading=h.l51fcryky9x). I don't know when I'll get back to this, but I suggest you take a look when you can and add items and/or comments as you see fit. We can then get together to discuss whether the structure will work and what the next steps should be.

**Comment by pioterj** [comment]
@bamboo Who is reviewing this story? Last update is in November last year.

**Comment by bamboo** [comment]
@pioterj It didn't become our priority yet.

**Comment by pioterj** [comment]
I'd put it back to the backlog then.

**Comment by bamboo** [comment]
Why?

**Comment by pioterj** [comment]
I interpret "in review" as actively being reviewed, similarly to "in progress" as actively being worked on.

**Comment by bamboo** [comment]
Fair enough. We've been using that column as "ready for review" and usually take items from there first, except for this particular documentation issue as you noticed. Notice the milestone field is set to a later milestone as well.

**Comment by pioterj** [comment]
Given the change of approach in favour of https://github.com/gradle/gradle-script-kotlin/issues/317, I guess we can close this?

**Comment by bamboo** [comment]
Good point, @pioterj.
