### ISSUE TITLE
Build scripts outside the imported project can be edited with the correct classpath

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#181]

**Comment by eskatos** [comment]
LGTM 👍 
Nice coverage!

Theses changes cover #130 too, right?

**Comment by bamboo** [comment]
Thanks, Paul!

These changes were initially motivated by #130 but they were independent enough that I decided to create a separate issue.

#130 became only about the sub-project classpath of a multi-project build.
