### ISSUE TITLE
Portal plugins can be applied via type-safe, tooling-friendly mechanism

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#185]
Grab metadata from the plugin portal and generate extension members for type-safe, tooling-friendly plugin application.

This is mostly about prototyping and playing with the IDEA to assess its coolness potential.

**Comment by bamboo** [comment]
Since the regular full-stop dot is not a valid member name character in Kotlin, the [ONE DOT LEADER](http://www.fileformat.info/info/unicode/char/2024/index.htm) character can be used as a replacement. Here's a complete working prototype, as expected code completion works nicely inside the plugins block:

```
class PluginsBlockExample {

    fun example() {
        
        plugins {
            `maven-publish` version "1.+"
            `org․jetbrains․dokka`
            application
        }
        
    }

    fun plugins(block: PluginsBlock.() -> Unit) {
    }
}

class PluginsBlock {
    fun id(id: String): PluginId = PluginId(id)
}

data class PluginId(val id: String, val version: String? = null) {
    infix fun version(version: String): PluginId = copy(version = version)
}

val PluginsBlock.application: PluginId
    get() = id("application")

val PluginsBlock.`maven-publish`: PluginId
    get() = id("maven-publish")

val PluginsBlock.`org․jetbrains․dokka`: PluginId
    get() = id("org.jetbrains.dokka")
```

Code completion will probably be even better after we take advantage of Kotlin 1.1-M03 scope control.

**Comment by bamboo** [comment]
Closing as complete.

We produced two prototypes.

The first one with a [flat plugin index](https://github.com/gradle/gradle-script-kotlin/tree/plugin-portal-index), where each plugin id is encoded as a Kotlin extension property. Unfortunately, the dot character is not allowed in member names so we had to resort to [a trick to make it look nice](https://github.com/gradle/gradle-script-kotlin/blob/dfb5477f507e6ac4d37bdb48317f02ba827cf30b/plugins/plugin-portal-index/buildSrc/src/main/kotlin/codegen/GeneratePluginPortalExtensions.kt#L110) which [prompted some valid concerns](https://github.com/gradle/gradle-script-kotlin/commit/1026331e04f712929ac6c6dcb535ffcd311e676e#commitcomment-20067635). 

![plugins-block](https://cloud.githubusercontent.com/assets/51689/21009288/feaaa066-bd2c-11e6-961e-778ad9cf3ce1.gif)

The second one, only possible thanks to a great insight from @eskatos, with a [hierarchical plugin index](https://github.com/gradle/gradle-script-kotlin/tree/hierarchical-plugin-portal-index). In this second one, the dot character preserves its usual meaning and doesn't have to specially encoded in the plugin id: 

![out](https://cloud.githubusercontent.com/assets/51689/21009436/b0baae0e-bd2d-11e6-871f-2a5d505434b9.gif)

We should have enough to think about, discuss and take a decision in the upcoming iterations.

**Comment by mkobit** [comment]
This is absolutely awesome, and both of the screen caps have me very excited to use this feature. I know this issue was for portal plugins, but is there a way to extend this for custom `pluginRepositories` definitions, or is it already supported?

**Comment by bamboo** [comment]
Hi @mkobit, thanks for the feedback! Right now this is only a prototype working against the Gradle plugin portal but we'll definitely want to make it easy to work with custom `pluginRepositories` as well when we ship it.
