### ISSUE TITLE
Update extra delegated properties operators to enable them in scripts

### ISSUE THREAD

**Issue by orangy** [gradle/gradle-script-kotlin#195]
https://github.com/gradle/gradle-script-kotlin/blob/75f6ad011cd32c6ad2d8a607c5fa7555b6fa4769/src/main/kotlin/org/gradle/script/lang/kotlin/ExtraPropertiesExtensions.kt#L33-L33

> Not really useful in the current setting until Kotlin supports local delegated properties (http://kotlin.link/articles/Kotlin-Post-1-0-Roadmap.html)

This is supported in Kotlin 1.1-M03, but you need to change `Nothing?` to `Any?` in getValue/setValue signatures.

**Comment by sdeleuze** [comment]
That would be very useful to be able to do that!

**Comment by bamboo** [comment]
@orangy `Nothing?` seems to work just fine, the real problem is that Kotlin chokes on top level delegated extra property definitions.

**Comment by orangy** [comment]
`Nothing?` can work when there is no "receiver" instance, since it is `null` which is assignable to `Nothing?`. When in a script, receiver is actually a `Project` and it cannot be assigned to `Nothing?`, because it is not null.

**Comment by bamboo** [comment]
Thanks, @orangy, it makes sense. I still find it a bit confusing that `Nothing?` would work inside a nested function or block but not at the top level.
