### ISSUE TITLE
Support convenience configuration of existing objects in NamedDomainObjectContainer

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#200]
Invocation syntax is a possible candidate:

```kotlin
tasks("clean") {
  doLast {
    file("target/").delete()
  }
}

```

Would be equivalent to:

```
tasks.getByName("clean").apply {
  doLast {
    file("target/").delete()
  }
}
```

Could also be used to access typed tasks:

```kotlin
// just a name 
tasks(MyTaskNames.CHECK) {
}

// name and type
tasks(name = MyTaskNames.CHECK, type = MyCheck::class) {
}
```

Configuring a source set would be similar to:

```kotlin
sourceSets("main") {
  java.srcDirs += file("src/generated/java")
}
```

Delegate properties might provide a good alternative:

```kotlin
val clean by tasks {
  doLast {
    file("target/").delete()
  }
}

val `oddly-named-task`: SomeTask by tasks {
  someTaskProperty = "foo"
}
```

**Comment by oehme** [comment]
Can Kotlin do

```
sourceSets {
  "main" {

  }
}
```

?

**Comment by bamboo** [comment]
@oehme, yes and I was considering to use that syntax for #35 since it implies a cardinality of _many_ and it's similar to the Groovy version.

**Comment by oehme** [comment]
If it can do that, can it also do `sourceSets."main"`?

**Comment by bamboo** [comment]
No, not that but it can do `sourceSets["main"]`.

**Comment by oehme** [comment]
I think that's even better when you think of it as a container or map.

**Comment by bamboo** [comment]
@oehme, I agree that for accessing an existing element it probably won't get better than that. 

How do you envision the configuration of an existing source set, for example?

**Comment by oehme** [comment]
```
sourceSets["test“].compileClasspath = configurations["compileClasspath"] + sourceSets["main“].output
```

**Comment by bamboo** [comment]
Must be designed together with #35.

**Comment by bamboo** [comment]
Consider also the contrast between eager and lazy configuration methods such as `getByName` and `withType`.

**Comment by bamboo** [comment]
As of #35, it is now possible to select and configure tasks with the following patterns:

## Select single task by name

Use the collection indexer.

```
task["jar"].dependsOn("someOtherTask")
```

## Configure multiple tasks by name

Invoke the task container (works with any `DomainObjectContainer`).

```
tasks {
    "jar" {
         dependsOn("someOtherTask")
    }
    
    "clean"(Delete::class) { // specify type information so `delete` is available
         delete("someOtherDir")
    }
}
```

## Bring a task into scope for multiple references

Declare a delegated property using the container as a delegate (works with any `DomainObjectCollection`).

```
val jar: Jar by tasks
jar.apply {
    from(sourceSets["main"].allSource)
    from(sourceSets["test"].allSource)
}

tasks["build"].dependsOn(jar)
```
