### ISSUE TITLE
Add helper for `useTestNG` setting options on test

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle-script-kotlin#206]
Something like this should be sufficient:

```kotlin
fun Test.useTestNG(options: TestNGOptions.() -> Unit) {
    useTestNG(closureOf(options))
}
```

Not sure where this should be added.

**Comment by eskatos** [comment]
Thanks for the report @JLLeitschuh 

It applies to a bunch of `Test` task's methods, e.g. `useJUnit` is affected too.
We need to add type-safe methods for these in the `Test` task to fix this properly.

**Comment by eskatos** [comment]
See https://github.com/gradle/gradle/pull/1202
