### ISSUE TITLE
Outline API Reference

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#209]
Generate Gradle Script Kotlin API docs using [Dokka](https://github.com/Kotlin/dokka).

Similar to the [Gradle javadoc](https://docs.gradle.org/current/javadoc/) but including gradle-script-kotlin API extensions.

The API should be shown with Kotlin syntax (even the Gradle API).

**Comment by eskatos** [comment]
A first cut of an API doc generated using Dokka is now available: https://gradle.github.io/gradle-script-kotlin-docs/api/

The corresponding build can be found here: https://github.com/gradle/gradle-script-kotlin-docs

The Gradle API definition has been copied from the Gradle build, we should find a way to share that explicitly instead.

**Comment by eskatos** [comment]
I did look into all the dokka warnings and the `<ERROR CLASS>` in the html output.
They come from usage of Gradle internal APIs which we don't provide to dokka.
e.g. https://gradle.github.io/gradle-script-kotlin-docs/api/org.gradle.script.lang.kotlin.cache/-script-cache/index.html
We need to filter GSK internals out.

**Comment by eskatos** [comment]
Once #348 is in, the [API docs](https://gradle.github.io/gradle-script-kotlin-docs/api) contain:
- the Gradle public API with Kotlin signatures, see e.g. the [`JavaExec` task](https://gradle.github.io/gradle-script-kotlin-docs/api/org.gradle.api.tasks/-java-exec/index.html)
- the Gradle Script Kotlin API, including generated extensions, see e.g. the [`DisplayAccessors` task](https://gradle.github.io/gradle-script-kotlin-docs/api/org.gradle.script.lang.kotlin.accessors.tasks/-display-accessors/index.html) and the [`DependencyHandler`extensions](https://gradle.github.io/gradle-script-kotlin-docs/api/org.gradle.script.lang.kotlin/org.gradle.api.artifacts.dsl.-dependency-handler/index.html)
- the Gradle built-in plugins accessors, see e.g. the [`application` accessor](https://gradle.github.io/gradle-script-kotlin-docs/api/org.gradle.script.lang.kotlin/org.gradle.api.-project/application.html)

The only remaining `<ERROR CLASS>` are on two extensions of Gradle internal types that the built-in plugins exposes:
- [`defaultArtifacts`](https://gradle.github.io/gradle-script-kotlin-docs/api/org.gradle.script.lang.kotlin/org.gradle.api.-project/default-artifacts.html) (`DefaultArtifactPublicationSet`)
- [`toolChains `](https://gradle.github.io/gradle-script-kotlin-docs/api/org.gradle.script.lang.kotlin/org.gradle.api.-project/tool-chains.html) (`NativeToolChainRegistryInternal`)
