### ISSUE TITLE
Automatically generate type-safe accessors for contributed extensions

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#235]
Apply plugins block against empty project and see which extensions are added.

Then use code generator and build script compiler as in the [metadata file driven solution](233).

* pros
   * it is automatic
* cons
   * won't take imperative plugins into account

**Comment by bamboo** [comment]
![type-safe-accessors](https://cloud.githubusercontent.com/assets/51689/23306275/91203172-fa81-11e6-9232-0827ca695744.gif)

**Comment by pioterj** [comment]
I can't reproduce what I see in the screencast. Is it on master yet?

**Comment by bamboo** [comment]
It is.

You have to be running the latest Kotlin plugin from the EAP channel (`1.1.0-rc-91-*`) and reimport `samples/hello-world`.

**Comment by pioterj** [comment]
Thanks, @bamboo. It's working for me with Kotlin plugin 1.1.0-release-IJ2016.3-1.

I ended up cloning a fresh copy of the project to make it work. "Refresh all Gradle projects" and importing project again didn't help.
