### ISSUE TITLE
Add a note about needing to configure settings.gradle to readme

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle-script-kotlin#236]
Would be helpful to get people started if the readme called out to the fact that you need to configure your `settings.gradle` file to point to the `kts` file.

**Comment by AlexCzar** [comment]
Yup, wasted an hour figuring this out, if not for @JLLeitschuh, I would've abandoned the effort for now.

**Comment by bamboo** [comment]
https://github.com/gradle/gradle-script-kotlin#limitations
