### ISSUE TITLE
Fix '[class]loader constraint violation' errors

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#25]
During the partial migration of Gradle Script Kotlin's own build (#24), an attempt was made to port the following task from Groovy to Kotlin:

```kotlin
task<Zip>("repackageKotlinCompilerEmbeddable") {
    baseName = "kotlin-compiler-embeddable"
    version = "${kotlinVersion}a"
    extension = "jar"
    entryCompression = ZipEntryCompression.STORED
    from(Callable {
        val files = configurations.getByName("compile").files
        zipTree(files.single { it.name.startsWith(baseName) })
    })
    exclude("META-INF/services/java.nio.charset.spi.CharsetProvider")
    destinationDir = buildDir
    description = "Repackages '$baseName:$version' to remove broken META-INF/services files"
}
```

It was then reverted, because it caused the following error:

> loader constraint violation: when resolving method "org.gradle.script.lang.kotlin.ProjectExtensionsKt.task(Lorg/gradle/api/Project;Ljava/lang/String;Lkotlin/reflect/KClass;Lkotlin/jvm/functions/Function1;)Lorg/gradle/api/Task;" the class loader (instance of org/jetbrains/kotlin/codegen/GeneratedClassLoader) of the current class, Build_gradle, and the class loader (instance of org/gradle/internal/classloader/MutableURLClassLoader) for the method's defining class, org/gradle/script/lang/kotlin/ProjectExtensionsKt, have different Class objects for the type kotlin/reflect/KClass used in the signature

This issue is about tracking down and fixing that error, and when complete, migrating the task above as originally intended

**Comment by bamboo** [comment]
I could track it down to the presence of Kotlin code in `buildSrc`.

**Comment by bamboo** [comment]
I think it makes sense to postpone this until we're ready to tackle #38.

**Comment by bamboo** [comment]
A complete repro can be found in [bamboo/gradle-script-kotlin-issue-25](https://github.com/bamboo/gradle-script-kotlin-issue-25).

**Comment by bamboo** [comment]
Related to #84
