### ISSUE TITLE
Consider adding type safe accessors for Gradle conventions

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle-script-kotlin#250]
See #159 that addressed Gradle extensions.
In particular this https://github.com/gradle/gradle-script-kotlin/issues/159#issuecomment-274012554.

**Comment by eskatos** [comment]
Lots of plugins still rely on conventions.

In Gradle:
- `antlr` adds `AntlrSourceVirtualDirectory` to antlr source sets
- `project-reports` adds `ProjectReportsPluginConvention` to `Project`
- `ear` adds `EarPluginConvention` to `Project`
- `jetty` adds `JettyPluginConvention` to `Project`
- `maven` adds `MavenPluginConvention` to `Project`
- `osgi` adds `OsgiPluginConvention` to `Project`
- `application` adds `ApplicationPluginConvention` to `Project`
- `base` adds `BasePluginConvention` to `Project`
- `groovy-base` adds `GroovySourceSet` to Groovy source sets
- `java-base` adds `JavaPluginConvention` to `Project`
- `war` adds `WarPluginConvention` to `Project`
- `scala` adds `ScalaSourceSet` to Scala source sets

**Comment by eskatos** [comment]
WRT Kotlin support for Gradle conventions we have two options:

1. Push forward the use of extensions instead of conventions in Gradle and rely on #159
2. Expose Gradle conventions namespaced in Kotlin build scripts.

About **1**, see https://github.com/gradle/gradle-script-kotlin/issues/159#issuecomment-274012554 for more information about the migration path.

**2** is possible thanks to the fact that conventions are addressable by name in the Gradle API. 
We could expose existing conventions as if they were extensions.

For example, the `ApplicationPluginConvention` applied to `Project` by the `application` plugin would allow you to do the following:

    application {
        mainClassName = "com.acme.Main"
    }

Which is different from what it looks in Groovy build scripts: 

    mainClassName = "com.acme.Main"

but solves potential naming conflicts by namespacing conventions.

**Comment by bamboo** [comment]
We should probably do (1) and (2).

Doing (1) by following @adammurdoch's suggestion:

> This will probably be some method on ExtensionContainer to register the extension as both a convention object and an extension.

So Gradle core plugins can start exposing their conventions as extensions.

And (2) to provide a type-safe mechanism for Kotlin build script authors to consume conventions contributed by community plugins while they migrate to extensions at their own pace.

**Comment by adammurdoch** [comment]
+1. It would also be nice if the type-safe mechanism for convention objects were similar to the type-safe mechanism for extension objects.

**Comment by adammurdoch** [comment]
We might think about always exposing every convention object also as an extension (taking backwards compatibility into account) instead of adding a type-safe mechanism for convention objects.

**Comment by eskatos** [comment]
> We might think about always exposing every convention object also as an extension (taking backwards compatibility into account) instead of adding a type-safe mechanism for convention objects.

Yup, we thought about that. See point 2 above.
We should do that in Gradle core instead of in GSK so the Groovy DSL benefit from the change too.

In Kotlin build scripts you would only get type-safe accessors for 'namespaced' conventions.
In Groovy build scripts you would get both direct access and namespaced access to conventions.

WRT. backwards compatibility the only issue I see for now are name conflicts.
What if both a convention and an extension have the same name?
I did not consider yet how frequent that could be.
But we could simply enforce that this is not possible in `DefaultConvention`.
Or favor extensions over conventions, meaning that in the case of a naming conflict, only the extension is considered in DSLs and that to access the convention you would have to use the API explicitly.
WDYT @adammurdoch ?

**Comment by bamboo** [comment]
Fixed as part of #159.
