### ISSUE TITLE
Unresolved reference setUrl in build.gradle.kts

### ISSUE THREAD

**Issue by DaanDeMeyer** [gradle/gradle-script-kotlin#255]
Intellij indicates the setUrl function in the maven { } block as a unresolved reference. It happens with the latest distribution (https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.5-20170120180718+0000-all.zip) but not with the 0.7 release distribution (https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.4-20170117200919+0000-all.zip).

Building the project works without any problems so it seems like it's an error by Intellij but since it doesn't happen with the 0.7 wrapper I thought I'd post the issue here first.

Platform: Windows 10
Kotlin plugin version; 1.1.0-beta-17
Intellij version: 2016.3.3
Gradle wrapper: https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.5-20170120180718+0000-all.zip

**Comment by bamboo** [comment]
Blocked by #157.

**Comment by bamboo** [comment]
Resolved in a7308886672047171bcddcb9979c0a22295f925f with latest IntelliJ Kotlin plugin from the 1.1 EAP channel.
