### ISSUE TITLE
Review Buildship support for Kotlin build scripts

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#258]

**Comment by donat** [comment]
Related cards on the `gradle/buildship` board:
- [Buildship Kotlin Support Epic](https://github.com/gradle/buildship/issues/50)
- [Buildship Kotlin Support prototype](https://github.com/gradle/buildship/issues/126)

**Comment by donat** [comment]
The fundamental difference between IDEA and Eclipse is that in Eclipse you have to support multiple project root with individual setting.
