### ISSUE TITLE
Upgrading gradle-script-kotlin version

### ISSUE THREAD

**Issue by baron1405** [gradle/gradle-script-kotlin#261]
Is it possible to upgrade the version of gradle-script-kotlin without having a new release of Gradle? Grale 3.3 and 3.4 ship with 0.5.1 and it would be great to be able to use the latest published version (e.g. 0.7.0). It would definitely help to provide relevant and timely feedback.

**Comment by bamboo** [comment]
Hi @baron1405,

At the top of the [release notes](https://github.com/gradle/gradle-script-kotlin/releases/tag/v0.7.0) you can find instructions on how to configure the Gradle wrapper to use the latest gradle-script-kotlin release, copied here for your convenience:

```
$ cd $YOUR_PROJECT_ROOT
$ gradle wrapper --gradle-distribution-url https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.4-20170117200919+0000-all.zip
```

And in case you like living on the edge, you can always find the url for the Gradle snapshot with the development version of gradle-script-kotlin at https://github.com/gradle/gradle-script-kotlin/blob/master/gradle/wrapper/gradle-wrapper.properties#L6

Cheers!

**Comment by baron1405** [comment]
OK I see. Sorry for the confusion as I was looking for something I had to put in my buildscript. To be clear, this will get me a new version of Gradle that has the latest Kotlin script plugin. Is that correct?

**Comment by bamboo** [comment]
Correct.
