### ISSUE TITLE
KotlinBuildScriptModelRequest should take additional arguments

### ISSUE THREAD

**Issue by donat** [gradle/gradle-script-kotlin#265]
I'm currently checking how we can reuse gradle-script-kotlin as-is in Buildship. I found that KotlinBuildScriptModelRequest uses the following properties for querying the build script dependencies:

- projectRoot
- gradleHome
- gradleJavaHome
- gradleJvmOptions

On top of those, Buildship would need two extra arguments to pass to the connection
- Gradle user home
- arguments (to pass `--offline` for example)

**Comment by bamboo** [comment]
I will make `KotlinBuildScriptDependenciesAssembler` a proper API that can be used by both Buildship and IntelliJ.
