### ISSUE TITLE
KotlinBuildScriptModelRequest should support all Gradle distribution types for model queries

### ISSUE THREAD

**Issue by donat** [gradle/gradle-script-kotlin#266]
Currently, the Kotlin model query uses `GradleConnector.useInstallation(File)` to establish the TAPI connection: https://github.com/gradle/gradle-script-kotlin/blob/33ac0131bc008a86f7e2cd8f1035750699147c04/src/main/kotlin/org/gradle/script/lang/kotlin/support/KotlinBuildScriptModelRequest.kt#L60-L61

Unfortunately, in Buildship we don't know the location of the used Gradle distribution since the user can use all options provided by the TAPI: `useInstallation(File)`, `useGradleVersion(String)`, `useDistribution(URI)` and `useBuildDistribution()` are all available.

It would be great if we could pass all types of distributions to gradle-script-kotlin via the `environment` map.

For the record, here are the classes we use to serialize the distribution info and apply them on the TAPI connection:
- [GradleDistribution](https://github.com/gradle/tooling-commons/blob/d66745fec67e2474294e79919f29049a21b6dcf2/toolingclient/src/main/java/com/gradleware/tooling/toolingclient/GradleDistribution.java)
- [GradleDistributionSerializer](https://github.com/eclipse/buildship/blob/4113aac8d7ab3ee52305756432f24b3a8aa69dfb/org.eclipse.buildship.core/src/main/java/org/eclipse/buildship/core/util/gradle/GradleDistributionSerializer.java)

**Comment by oehme** [comment]
@donat could you help @bamboo by sending a pull request that adds support for "gradleVersion" and "distributionUrl" and falls back to the "buildDistribution" if none of the 3 is specified?

**Comment by donat** [comment]
I'll try.
