### ISSUE TITLE
Gradle script kotlin build for 3.4 release

### ISSUE THREAD

**Issue by baron1405** [gradle/gradle-script-kotlin#270]
Can we get a version of Gradle with the latest kotlin support based on the released version of Gradle 3.4. Thanks!

**Comment by baron1405** [comment]
Any update on this? I'd like to use the latest Kotlin script support for Gradle 3.4.

**Comment by baron1405** [comment]
I see updated 3.5 snapshots being created. Is the released 3.4 not going to be supported with the latest Kotlin script support?

**Comment by bamboo** [comment]
Hi @baron1405, 

The 3.4 release doesn't include all the APIs required by the latest `gradle-script-kotlin` version so this is not a trivial task. 

Do you absolutely require `3.4` or would you be able to use `3.5` once it's out?

**Comment by baron1405** [comment]
The problem is that I am currently using 3.4 with the now ancient 0.5.0 script support. I do not want to switch to the 3.4 SNAPSHOT from January as it has known bugs. I cannot put 3.5 into production so I am stuck with using 0.5.0 with the released 3.4. It would be great for me and I suspect others to be able to use a newer release (e.g. 0.7.0) of the script support in the released 3.4. I completely understand that this may be a tough to accommodate but on the other hand you will get a lot more users and testing done on the new version of the script support if it were available based on a production release (i.e. 3.4). Thanks for considering the request!

**Comment by baron1405** [comment]
Just curious whether you can do a release using Gradle 3.4 and version 0.7.0 of the Kotlin support. At least that gets us a number of significant new features since 0.5.0. Is that possible?

**Comment by baron1405** [comment]
So is creating a package with Gradle 3.4 and script support 0.7.0 something that can happen or should I wait for Gradle 3.5 to be released?

**Comment by bamboo** [comment]
I'm attempting a build of Gradle 3.4.1 and 0.7.0 from [this branch](https://github.com/gradle/gradle/tree/rbo-v3.4.1-gsk-v0.7.0).

Let's see if it goes through CI cleanly. Otherwise I'm afraid Gradle 3.5 it will be.

**Comment by baron1405** [comment]
Great news and thanks in advance for taking the time to try it!

**Comment by baron1405** [comment]
Congratulations on the 0.8.0 release! I see in the release notes that 0.8.0 is going to be included in Gradle 3.5. Looking at the Gradle source code in master as of 3/9 the dependency still appears to be on 0.5.1. That was a little surprising to me.

**Comment by bamboo** [comment]
Thanks, @baron1405.

The upgrade to `0.8.0` has been published to the release branch.

**Comment by baron1405** [comment]
Going to close this since 3.5 will have the latest and greatest.

**Comment by baron1405** [comment]
Looks like the 3.5 0.8.0 commit got reverted. See https://github.com/gradle/gradle/commit/dbbae6d03ee4fa692bcf778b3e1dcbcdcaa7d5c1

**Comment by bamboo** [comment]
Thanks for the heads up, @baron1405!

**Comment by baron1405** [comment]
I also commented on the Gradle forum https://discuss.gradle.org/t/whats-the-roadmap-for-gradle-script-kotlin/21936

**Comment by eskatos** [comment]
Quoting @jjohannes from the forum:

> The upgrade to Gradle Script Kotlin 0.8.0 will be part of the 3.5 release.
>
> We removed it from the branch yesterday, because it caused an issue with our integration test setup and that blocked other features on the release branch. We have resolved the issue now and will add the upgrade to the release branch again within the next hours.

**Comment by baron1405** [comment]
I was very happy to hear that!
