### ISSUE TITLE
Build author can navigate to the gradle-script-kotlin sources

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#281]
As a workaround to #193, gradle-script-kotlin sources should be included in the Gradle all distro.

**Comment by bamboo** [comment]
Tried copying `gradle-script-kotlin` sources to Gradle's distro `src` folder to no avail.

**Comment by pioterj** [comment]
With https://github.com/gradle/gradle-script-kotlin/issues/193 closed should this story be closed too?

**Comment by bamboo** [comment]
This should also include navigating to the generated accessors which is currently not implemented.

**Comment by bamboo** [comment]
![source-code-navigation](https://cloud.githubusercontent.com/assets/51689/25772994/1fb02b2a-324c-11e7-91aa-8c7e51c86d86.gif)
