### ISSUE TITLE
Publish a JAR with tooling API models

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle-script-kotlin#304]
So consumers can depend on it without depending on the whole GSK jar.

For now this is limited to `org.gradle.script.lang.kotlin.resolver.KotlinBuildScriptModel`

Motivated by https://github.com/eclipse/buildship/issues/412

**Comment by bamboo** [comment]
Blocked by #293.

**Comment by eskatos** [comment]
Model: [org.gradle.script.lang.kotlin.tooling.models.KotlinBuildScriptTemplateModel](https://github.com/gradle/gradle-script-kotlin/blob/master/tooling-models/src/main/kotlin/org/gradle/script/lang/kotlin/tooling/models/KotlinBuildScriptTemplateModel.kt).

Module: `org.gradle:gradle-script-kotlin-tooling-models`

@donat it will be published as part of `0.9.0`. A snapshot is available.
