### ISSUE TITLE
Create documentation landing pages for all core plugins

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#314]
The javadoc for the plugin id extension members such as `java`, `application`, etc, include direct links to the User Guide generated directly from the plugin id. Some of the targeted anchors are currently missing.

**Comment by eskatos** [comment]
A simple mapping in GSK build could do.

**Comment by bamboo** [comment]
A more complete solution in the future could allow plugins to advertise their own help pages via an additional plugin properties file property.

**Comment by eskatos** [comment]
I added some more links.

Otherwise LGTM!
