### ISSUE TITLE
Remove `ProjectExtensionsTaskRegistrationAction` configuration overhead

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#320]
Execution cost should only be paid by Kotlin based projects.

An alternative implementation would be to introduce a service that reacts to Kotlin build script evaluation events and registers the tasks as needed.

**Comment by bamboo** [comment]
A better strategy would be to apply a plugin to the root project from `KotlinScriptPlugin`. That plugin would register the `gskGenerateAccessors` task.

**Comment by eskatos** [comment]
This has been merged
