### ISSUE TITLE
'maven-publish' plugin with the 'java-library' plugin does not include dependencies that are added after publication creation

### ISSUE THREAD

**Issue by mkobit** [gradle/gradle-script-kotlin#327]
### Expected Behavior

Dependencies added after a `MavenPublication` is created should also be in the POM descriptor.

### Current Behavior

The API dependencies are different in `.kts` build scripts compared to Groovy build scripts.

### Context

Trying to configure a Maven publication in a GSK script.

### Steps to Reproduce (for bugs)

1. `git clone https://github.com/mkobit/gradle-java-library-maven-publishing-problem.git`
1. `./gradlew generatePom`
1. Open up `invalid-library-example/build/publications/mavenJavaLibrary/pom-default.xml` and view the generated publication POM
1. `./gradlew clean generatePom -PuseKts` to generate using what I believe is the same script configured for GSK
1. Open up `invalid-library-example/build/publications/mavenJavaLibrary/pom-default.xml` and see the different in the `compile` scope dependencies in the generated publication POM have both `guice` and `apache-commons` missing

### Your Environment

* Gradle 3.5-rc-3
 * Build scan URL: for Groovy based - https://gradle.com/s/yawb4ziqpisnk
 * Build scan URL: for Kotlin based - https://gradle.com/s/6fb7fywdtfjla

**Comment by mkobit** [comment]
I updated the repository to also demonstrate the problem with `implementation` as well.

**Comment by mkobit** [comment]
I've updated the description and pushed up smaller example to at least demonstrate more of what I am running into.

**Comment by bamboo** [comment]
Thanks for the report!
