### ISSUE TITLE
Integration test samples

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle-script-kotlin#345]
The `check-` task rule of the `gradle-script-kotlin` build runs the `tasks` task on samples.
This is not enough, we need to actually run tasks defined in samples and assert they work as expected.

**Comment by eskatos** [comment]
Most of the work is done in the [pm-integ-testing-samples](https://github.com/gradle/gradle-script-kotlin/compare/pm-integ-testing-samples) branch.

A `samplesTest` source set contains integration tests for samples.

As an opportunistic refactoring, unit tests and integrations tests were also split between the `test` source set and a new `integTest` source set.

Some integration tests are not moved to `integTest` yet because they need to access `internal` members from the production code and this doesn't work for added source sets. It does for the `test` source set though. To be continued.

**Comment by eskatos** [comment]
This is now done and we have proper test reports on CI: https://builds.gradle.org/repository/download/GradleScriptKotlin_CheckSamples/2838019:id/reports/tests/samplesTest/index.html

**Comment by bamboo** [comment]
Very nice!
