### ISSUE TITLE
Support convenient creation of objects within NamedDomainObjectContainers

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#35]
### String invocation (Monomorphic container)
```kotlin
container {
  "new-item-a" {
     newItemProperty = false
  }
  "new-item-b" {
  }
}
```

###  String invocation (Polymorphic container)
```kotlin
container {
  "new-item-a"(type = JvmLibrary::class) {
     jvmLibraryProperty = "foo"
  }
  "new-item-b"(type = JvmApplication::class)
}
```

### Eager delegated properties (Monomorphic container)

```kotlin
val newItemA by container {
  newItemProperty = false
}

val newItemB by container(name = "new-item-b")

val myConfig by configurations // will create if it's not there, return existing if it's there
val myConfig by configurations.existing // will not create

// or maybe the opposite
val myConfig by configurations.new // will create if it's not there, fail if it's already there
val myConfig by configurations.newOrExisting // will create if it's not there, return existing if it's there
val myConfig by configurations // will not create, throw if it's not there
val myConfig: Configuration? by configurations // return null if it's not there
val myConfig by configurations.existingOrNull
```

### Eager delegated properties (Polymorphic container)

```kotlin
val newLib: JvmLibrary by container {
  jvmLibProperty = "foo"
}
val newApp: JvmApplication by container
```

**Comment by cbeams** [comment]
Note that this is _possible_ now using, for example `tasks.create(...)` (where `tasks` itself is a `NamedDomainObjectContainer`)—it's just not terribly _convenient_ to do so. It isn't as _declarative_ as it might be.

Moving this to 1.0 M3, where these sorts of improvements will be a common theme

**Comment by bamboo** [comment]
We decided to provide two ways of configuring domain object containers and their elements. First, a declarative approach, better suited to configuring many objects at once, and another one based on delegated properties, better suited to configuring single objects or simply bringing them into scope.

## 1. Bulk configuration

### Monomorphic containers

```kotlin
container {
  "new-item-a" {
     newItemProperty = false
  }
  "new-item-b" {
  }
  "new-item-c"() // invocation without passing a block also works
}
```

###  Polymorphic containers

```kotlin
container {
  "new-item-a"(JvmLibrary::class) {
     jvmLibraryProperty = "foo"
  }
  "new-item-b"(type = JvmApplication::class) // can use explicit parameter name for clarity
  "new-item-c"() // create element with default type 
}
```

## 2. Selective access/configuration

### Via delegated properties

#### Bringing an existing element into scope

```kotlin
val clean by tasks // brings an existing task into scope by name

val clean: Delete by tasks // brings an existing task into scope by name and type
```

#### Creating new elements

```kotlin
val clean: Delete by tasks.new { // creates a new object in the container
    delete("build")
}
```

#### Creating or configuring existing elements

```kotlin
val clean: Delete by tasks.newOrExisting { // creates or configures an object in the container
    delete("build")
}
```

### Via collection indexer

Collection elements can also be accessed via index:

```kotlin
val clean = tasks["clean"]

tasks["build"].apply {
  dependsOn(clean)
}
```

**Comment by bamboo** [comment]
Task description has been updated with the implemented solution.
