### ISSUE TITLE
Plugins written in Kotlin can use the same dsl as Kotlin build scripts

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle-script-kotlin#366]
`kotlin-dsl` plugin

This entails:
- making our customisations to the Kotlin compiler available as a standalone Kotlin compiler plugin
- `gradleScriptKotlinApi()`

**Comment by eskatos** [comment]
About providing `gradleScriptKotlinApi()` dependency to production code where `kotlin-dsl` plugin is applied.

```
gradleScriptKotlinApi = gradleApi + gradleApiExtensions + gradleScriptKotlinJars
```

`gradleApi` and `gradleScriptKotlinJars` are pretty straight forward.

But, `gradleApiExtensions` is generated source code, compiled and packaged as a jar. JIT and cached. Today it contains the type safe accessors for built-in gradle plugins. We could move this process to the GSK build to make it easier.

On the modularity aspect of things, the code that assemble `gradleScriptKotlinApi` currently sits into `:provider`. We'll probably need to extract this to a separate project shared by both `:provider` and `:plugins`.
