### ISSUE TITLE
Support automatic detection of Kotlin-based builds

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#37]
To use Kotlin build scripts, one has to set an *explicit*  `buildFileName` in his `settings.gradle` file:
```groovy
def configureGradleScriptKotlinOn(ProjectDescriptor project) {
    if(project.file('build.gradle.kts').exists()) {
        project.buildFileName = 'build.gradle.kts'
    }
    project.children.each { configureGradleScriptKotlinOn(it) }
}

include 'a', 'b', 'c'

configureGradleScriptKotlinOn rootProject
```

The [default value](https://github.com/gradle/gradle/blob/eab52800dd1fe372e9e64c9e50bcaa4029459a6c/subprojects/core/src/main/java/org/gradle/api/Project.java#L217) of `buildFileName` is `build.gradle`.

This issue is about removing the need to set an *explicit* `buildFileName`.

See also #56 for `settings.gradle.kts` support.

**Comment by eskatos** [comment]
In order to support automatic detection of Kotlin build scripts and settings scripts Gradle will need to get the supported file extensions as early as in its launcher and tooling-api provider connection.

The earliest usage is resolving the root directory of a build. The build layout depend on, among other things, the location of the settings script. Gradle needs the supported file extensions in order to resolve the settings script location.

The current SPI, `ScriptPluginFactoryProvider`, is too heavyweight and require management such as dependency injection. This is unsuitable. We need to introduce a new Gradle SPI that can be used very early and doesn't require any management.

```java
/**
 * Scripting language provider SPI.
 */
public interface ScriptLanguage {
    /**
     * Returns the file extension for scripts written in this script language.
     */
    String getExtension();
    /**
     * Returns the fully qualified class name of the {@link ScriptPluginFactoryProvider}
     * for this script language.
     *
     * Implementations can benefit from injection using {@link javax.inject.Inject}.
     */
    String getProvider();
}
```

Gradle will then use `getExtension()` to resolve settings scripts and build scripts files when bootstrapping a build and `getProvider()` to load the *heavyweight* script language support later, when needed.

**Comment by eskatos** [comment]
@bamboo the first PR against Gradle is ready for review https://github.com/gradle/gradle/pull/1908

Branches for all steps against Gradle are pushed:
![image](https://cloud.githubusercontent.com/assets/132773/25524235/14e836ee-2c0a-11e7-9368-ec4cc8d21855.png)

If you could have a look at the whole chain of changes it would be awesome.

**Comment by stephen-smith** [comment]
So weird, this isn't working for me on gradle 4.4.1.

```
% gradle --version
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.16
Ant:          Apache Ant(TM) version 1.10.5 compiled on March 28 2019
JVM:          1.8.0_232 (Private Build 25.232-b09)
OS:           Linux 5.3.0-22-generic amd64
% ls *.gradle*
build.gradle.kts  settings.gradle.kts
% gradle compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Task 'compileJava' not found in root project 'REDACTED'.

[...]

BUILD FAILED in 0s
% gradle -b build.gradle.kts compileJava

[...]

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

But, I can always just stick the buildFileName in settings.gradle.kts, I guess.

**Comment by nanodeath** [comment]
That version of Gradle is nearly 2 years old. At least try updating to 4.10.3.

**Comment by stephen-smith** [comment]
Sorry, I will continue using the latest version available in Debian buster (build box) and Ubuntu bionic (my laptop).

**Comment by melix** [comment]
Debian versions are _not_ official Gradle releases. They are repackaged releases with different dependencies. This is what the _official_ release would tell you:

```
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2017-12-20 15:45:23 UTC
Revision:     10ed9dc355dc39f6307cc98fbd8cea314bdd381c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_161 (Oracle Corporation 25.161-b12)
OS:           Linux 5.3.11 amd64
```

See how both Groovy and Ant versions are different? And that's just the surface. You should really avoid using the distro releases...
