### ISSUE TITLE
Make classes defined in buildSrc (in whichever language) visible to kotlin build scripts at compile time

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#38]

**Comment by adammurdoch** [comment]
The title is a little ambiguous. It could mean:

- Make classes defined in buildSrc (in whichever language) visible to kotlin build scripts at compile time
- Allow buildSrc classes to be implemented in kotlin.
- Allow the build scripts for buildSrc to be implemented in kotlin.

**Comment by bamboo** [comment]
It's the first meaning that we intended to capture here so I renamed it as per your suggestion, thanks.

**Comment by bamboo** [comment]
Make sure navigating to sources from `build.gradle.kts` to `buildSrc` works in IDEA.
