### ISSUE TITLE
KT-12549: Classes within kotlin-compiler-embeddable are shaded but their corresponding META-INF/services files are not

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#42]
Tracking issue for https://youtrack.jetbrains.com/issue/KT-12549

> In gradle-script-kotlin, we have had to rebuild the kotlin-compiler-embeddable jar and publish a custom release of it in order to exclude its problematic  META-INF/services/java.nio.charset.spi.CharsetProvider  file. The problem is that the file refers to the original name of a class that has since been shaded (repackaged) in the kotlin-compiler-embeddable jar. If the file is not removed (or edited to have the correct content), service loading / class loading errors occur at runtime in Gradle.

This problem was the reason we had to cut `1.0 M1a` and is also described in [its release notes](https://github.com/gradle/gradle-script-kotlin/releases/tag/v1.0.0-M1a).

**Comment by cbeams** [comment]
Per https://youtrack.jetbrains.com/issue/KT-12549#comment=27-1452516, there is now a dev build available that fixes this problem:

> Please try build 1.0.3-eap-14  from kotlin-dev Bintray channel (repository URL: https://dl.bintray.com/kotlin/kotlin-dev)

@bamboo, let's validate as soon as possible. I'm moving this into `Current`.

**Comment by bamboo** [comment]
I don't think the `1.0.*` series includes the API we need.

**Comment by ligee** [comment]
This is fixed in kotlin master and should work properly in 1.1.0-dev-998

**Comment by cbeams** [comment]
Thanks, @ligee. @bamboo please confirm this is indeed resolved when upgrading to `1.1.0-dev-998` as part of #44.

**Comment by cbeams** [comment]
Closing, as we believe this is fixed with the upgrade to `1.1.0-dev-998`, note that we've created #65 in order to verify that it is indeed fixed. For reference, the integration test that failed and exposed this problem originally was [`IsolatedAntBuilderMemoryLeakIntegrationTest`](https://builds.gradle.org/viewLog.html?buildId=808425&tab=buildResultsDiv&buildTypeId=Gradle_Master_CommitPhase_LinuxCommit_LinuxCommitJava18_4LinuxCommitJava18).
