### ISSUE TITLE
Support automatic creation of IDEA library on project import

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#43]
Per the [current instructions for working with our samples](https://github.com/gradle/gradle-script-kotlin/tree/v1.0.0-M1a/samples#patch-idea-configuration-for-the-project), it is necessary to run `./gradlew patchIdeaConfig` in order to create an IDEA library containing all the correct Kotlin and Gradle classpath entries for the IDEA project.

This should be done automatically on project import. When complete, we'll be able to eliminate the `patchIdeaConfig` step completely.

**Comment by cbeams** [comment]
@ligee, I've assigned this to you and put it `In Progress`, as I believe that reflects our last conversation. Please comment and/or otherwise update the issue if anything has changed.

**Comment by cbeams** [comment]
This feature is blocking completion of #55.

**Comment by cbeams** [comment]
@ligee, could you provide an update on this? Still possible in time for M2?

**Comment by bamboo** [comment]
Blocked by #76.
