### ISSUE TITLE
Cannot upgrade to Kotlin plugin builds beyond dev-372

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#44]
We attempted to update to a dev build newer than `dev-372` ([dev-467](https://teamcity.jetbrains.com/repository/download/bt345/769746:id/kotlin-plugin-1.1.0-dev-467.zip), to be precise), and were no longer able to perform navigation to source and quick documentation functions. Until this is resolved, we're "stuck" on `dev-372`, which means we're blocked on getting rid of the ugly workaround in `gradle-core` that forces us to [add source files to `gradle-*` binary jars](https://github.com/gradle/gradle/commit/4aa167c75a879e8172ae32908dbeb577855e4d51).

**Comment by cbeams** [comment]
@ligee, can you comment on this?

**Comment by cbeams** [comment]
This issue is blocking #55.

**Comment by ligee** [comment]
The conflicting functionality is (hopefully) removed from the latest releases (master: 1.1.0-dev-998). It doesn't unblock the issues related to navigation though - these will be addressed later separately.

**Comment by cbeams** [comment]
@bamboo, please upgrade to `1.1.0-dev-998` and confirm, thanks.

**Comment by cbeams** [comment]
Closing, as I've just confirmed with @bamboo that navigation to source and quick documentation do indeed work against `dev-998` builds of Kotlin libs and IDEA plugin.
