### ISSUE TITLE
_project_hidden_ should not show up in content assist

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#45]
Repro steps:

1. Follow the [instructions to set up a sample project within IDEA](https://github.com/gradle/gradle-script-kotlin/tree/v1.0.0-M1a/samples#patch-idea-configuration-for-the-project)
2. Open the project's `build.gradle.kts` file
3. Place the cursor at the left margin of the file, outside the context of any block or function
4. Press CMD-SPACE to get a content assist window
5. Notice that `_project_hidden_` is available for completion

`_project_hidden_` is an implementation detail of the way our integration with Kotlin Scripting works, and should probably be hidden from users (as its name suggests!)

**Comment by ligee** [comment]
`_project_hidden_` is no more in 1.1-M1 (and even in earlier builds in fact). But there is simply `project` now, which could be confusing as well. We are going to hide it some day, but that is probably another issue.

**Comment by bamboo** [comment]
Superseded by #88.
