### ISSUE TITLE
Adding a new line in a .kts file forces unwanted indentation

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#46]
Repro steps:

1. Follow the [instructions to set up a sample project within IDEA](https://github.com/gradle/gradle-script-kotlin/tree/v1.0.0-M1a/samples#patch-idea-configuration-for-the-project)
2. Open the project's `build.gradle.kts` file
3. Place the cursor after the closing brace (`}`) of any block or function
4. Press enter (or if Vim emulation is enabled `o`) to create a new line
5. Notice that the new line is indented in a "sticky" way that does not easily allow the user to get rid of it

**Comment by ligee** [comment]
fixed in 1.1-M1
