### ISSUE TITLE
Upgrade Groovy dependency from 2.4.6 => 2.4.7 and release 1.0-M1b

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#59]
_Chat transcript between @cbeams and @marc0der:_

Marco Vermeulen [12:15 PM]
I need to upgrade Groovy 2.4.6 in gradle-script-kotlin to 2.4.7

Chris Beams [1:28 PM]
@marco: why is the upgrade necessary?

Marco Vermeulen [1:29 PM]
It's causing the main gradle build to fail when building the shaded jar. It seems to be examining this build's deps.

Here's what I was seeing: https://builds.gradle.org/viewLog.html?buildId=867963&buildTypeId=Gradle_Master_CommitPhase_BuildDistributions&tab=buildLog.

So was hoping that upgrading to 2.4.7 would fix it.

Chris Beams [1:32 PM]
even if that _would_ fix it,

the distribution is pegged to gradle-script-kotlin 1.0.0-M1a

and we do not want to upgrade the distribution to gsk 1.0.0-SNAPSHOT

so we could try this out locally, see if it fixes the problem

and cut a 1.0.0-M1b if need be

but the point is that it's not quite as simple as just bumping the groovy version.

Marco Vermeulen [1:34 PM]
yeah that makes sense.

Chris Beams [1:35 PM]
what actually changed? why is the groovy 2.4.6 jar now just gone?

Marco Vermeulen [1:35 PM]
I haven't looked into it, was just going by what I saw in the failing build.

Chris Beams [1:55 PM]
@marco, the problem begins with the fact that dependency resolution in the distribution build is causing gradle-core's dependence on groovy-all 2.4.7 to take precedence over gradle-script-kotlin's dependency on groovy-all 2.4.6:

```
\--- org.gradle:gradle-script-kotlin:1.0.0-M1a
     +--- org.codehaus.groovy:groovy-all:2.4.6 -> 2.4.7
```

This wouldn't necessarily be a problem, except that the way that modules within the Gradle distribution declare their dependencies is rather rigid.

It happens in files that look like this:

```
/Work/gradle/gradle-script-kotlin[master]
$ cat ./build/generate-resources/main/gradle-script-kotlin-classpath.properties
projects=gradle-core,gradle-process-services
runtime=groovy-all-2.4.6.jar,slf4j-api-1.7.10.jar,javax.inject-1.jar,kotlin-stdlib-1.1.0-dev-372.jar,kotlin-reflect-1.1.0-dev-372.jar,kotlin-compiler-embeddable-1.1.0-dev-372a.jar,kotlin-runtime-1.1.0-dev-372.jar
```

note that first entry in `runtime`

declaring a dependence on `groovy-all-2.4.6`

these properties files determine each module's classpath at runtime

and `AllDistributionIntegrationSpec` and co blow up when they can't find the jar in question

because due to dependency resolution there is literally no groovy-all-2.4.6 present

just 2.4.7. there can be only one.

as a short term solution, we can indeed bump to 2.4.7 on the gradle-script-kotlin side as you suggested

and ship an M1b to make it available to the distribution build.

I need to talk to @rodrigo about whether we want to cut that from HEAD of gsk:master, or branch from gsk's 1.0-M1a, make the change there.

It just depends on what's happened on gsk:master since `M1a`

and the longer-term solution is that we need to think about how to deal with these kind of version mismatches between modules with common dependencies in a more flexible fashion.

the classpath.properties files were designed with the assumption of all modules being colocated and pinned to common versions of depedencies. With the introduction of (the externally managed) gradle-script-kotlin module, that assumption is no longer valid.

**Comment by adammurdoch** [comment]
You might move the calculation of the classpath to where we package the distribution, as the classpath properties is really just an artifact that the distribution uses for its own purposes rather than a public statement of dependencies. Then, the kotlin integration would just declare dependencies in the usual way, and the packaging would take care of calculating the final classpath to use when running from the distribution.

**Comment by cbeams** [comment]
Nice, thanks Adam. Will look at that.

**Comment by bamboo** [comment]
To be clear, this was resolved by following @adammurdoch's suggestion and moving the classpath computation to [where we package the distribution](https://github.com/gradle/gradle/blob/4c101a16625b9c02e40a43a293e28704bb7dd995/subprojects/distributions/distributions.gradle). `gradle-script-kotlin` dependency on Groovy was *not* yet bumped to 2.4.7 as that is no longer required (it might be required when we upgrade the Gradle distribution used to build `gradle-script-kotlin` itself).

**Comment by cbeams** [comment]
Issue moved to [gradle/core-issues #120](https://github.com/gradle/core-issues/issues/120) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by bigdaz** [comment]
Unfortunately, the gradle-script-kotlin module is still breaking the Gradle build. When running integration tests, we are creating a Gradle distribution based on the the resolved classpath, which includes the unpatched version of `gradle-script-kotlin`.

I'm going to dive into this and see if I can find a solution.
