### ISSUE TITLE
Guard against multiple buildscript blocks across scripts applied from one another

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#68]
For example, Gradle should fail fast in an `applyFrom("other.gradle.kts")` where `other.gradle.kts` is a build script containing a `buildscript` block.
- [ ] Verify the way Groovy-based Gradle scripts behave in the scenario above
- [ ] Replicate that behavior for Kotlin-based scripts

**Comment by oehme** [comment]
This would be different from how Gradle works until now. The `buildscript` block applies to the script it is defined in. Whatever is in `other.gradle.kts`'s `buildscript` block does not affect the script that applies `other.gradle.kts`.

This brings some limitations with it (e.g. can't apply plugins from another script), but I think we should stick with it to avoid further confusion around plugins. 

The new `plugins` DSL will get rid of this problem by properly modelling script plugins with their dependencies and exported classes etc.

**Comment by bamboo** [comment]
Superseded by #180
