### ISSUE TITLE
Add `action` extension method to ease use of methods that take closures

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle-script-kotlin#7]
A major ergonomic issue with the current Gradle API and Kotlin is the lack of equivalence for methods that take `groovy.lang.Closure`. Feels like the ergonomic equivalent in Kotlin for say `Project.copy(groovy.lang.Closure)` appears to be a function that takes an extension as an argument `fun copy(configure: CopySpec.() -> Unit)`, which is impossible to express in Java.

I'm interested in what the plan is for that. I see that key project configurations like `repositories` are getting exactly this treatment today. Is the plan to update the raw `Closure` definitions with correct type information and generate Kotlin extensions generated for all of these DSL methods? Or convert them to Kotlin for first class support?

Looks like there's always a `Action<T>` overload, so in the meantime, it'd be useful to have a convenience extension method to make the methods that take `Action` a little easier to use:

    fun <U> Project.action(exec: U.() -> Unit) = Action<U> { exec(it) }

That allows this kind of thing:

```
copy(action {
    from(files("build.gradle.kts"))
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
})
```

Rather than the alternatives:

```
// 1. Slightly clumsy, and problematic with nested closures

copy {
    it.from(files("build.gradle.kts"))
    it.duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// 2. Better, but for repeated calls a little messy

copy { spec ->
    spec.from(files("build.gradle.kts"))
    spec.duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// 3. Better still, but nesting is messy too

copy {
    it.run {
        from(files("build.gradle.kts"))
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
}
```

**Comment by bamboo** [comment]
Thanks for the suggestion, @DanielThomas!

We think we can provide a better long-term solution by carefully crafting the API jar given to the Kotlin compiler. Let us know what you think.

Superseded by #54.
