### ISSUE TITLE
Add Kotlin Gradle plugin to the Gradle plugin portal

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#71]
Tracking issue for https://youtrack.jetbrains.com/issue/KT-5756.

**Comment by cbeams** [comment]
@yole, you mentioned you might be willing to take care of this? The instructions are at https://plugins.gradle.org/docs/submit, and of course we'd be happy to help with anything you need along the way.

**Comment by cbeams** [comment]
@yole wrote:

> regarding putting our plugin into the plugin portal. the instructions make a (very reasonable) assumption that Gradle plugins are built with Gradle, but ours isn’t - it uses Maven. can I use the plugin publishing plugin to publish an artifact that wasn’t built with Gradle?

@yole, @tomdcc will get back to you as soon as possible on how to do this.

**Comment by nesl247** [comment]
FYI It looks like this was fixed according to the tracking issue.

**Comment by bamboo** [comment]
Thanks for the info, @nesl247.
