### ISSUE TITLE
KT-11128: Methods in the DSL that have `java.lang.Object` overloads are problematic

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle-script-kotlin#8]
Methods in the DSL that have Object overloads are problematic. Kotlin selects the least specific signature https://youtrack.jetbrains.com/issue/KT-11128. For example, this code will call `all(Object)`:

```
configurations.getByName("compile").resolutionStrategy.componentSelection.all { action ->
}
```

Hinting that the generic type doesn't help, this still selects `ComponentSelectionRules.all(Object)` and will fail at runtime:

```
componentSelection.all { action: ComponentSelection ->
}

```

So instead, you have to be a little more heavy handed and implement the Action:

```
componentSelection.all(Action<ComponentSelection> { selection ->
})
```

The extension I suggest in #7 would help in this case. Hopefully this is fixed to select the _most_ specific overload in Kotlin 1.1.0, but something to watch for.

**Comment by cbeams** [comment]
Thanks, @DanielThomas—we've organized this the same way we do with all other "tracking issues" around external Kotlin bugs, etc. We're watching the referenced issue in YouTrack as well.

**Comment by JLLeitschuh** [comment]
I just spent several hours on this myself.
This code (as of 0.5.0) gives this error:
```
Caused by: org.gradle.internal.rules.RuleActionValidationException: Type Project_gradle$2 is not a valid rule source:
- Must have at exactly one method annotated with @org.gradle.model.Mutate
        at org.gradle.internal.rules.RuleSourceBackedRuleAction.create(RuleSourceBackedRuleAction.java:73)
        at org.gradle.internal.rules.DefaultRuleActionAdapter.createFromRuleSource(DefaultRuleActionAdapter.java:55)
        ... 76 more

```
