### ISSUE TITLE
Support automatic detection of Kotlin-based subprojects

### ISSUE THREAD

**Issue by johnzeringue** [gradle/gradle-script-kotlin#80]
Related to #37, a root project that is configured by a `*.gradle.kts` file should automatically detect similar files in subprojects.

**Comment by mkobit** [comment]
Possibly related is importing a module.

Following the sample [README.md for importing a project on 0.2.0](https://github.com/gradle/gradle-script-kotlin/tree/v0.2.0/samples#import-the-sample-project-into-idea) works perfectly.

Reproduction steps:

Using IntelliJ 16.1.3 with https://teamcity.jetbrains.com/guestAuth/repository/download/bt345/805470:id/kotlin-plugin-1.1.0-dev-1303.zip

1. Create a new `Empty Project`
1. Open the `File -> Project Structure` window
1. Click the "Add" (plus sign) button and select `Import Module`
1. Select _hello-kotlin_ project

Expected: Autocomplete/classpath detection in _build.gradle.kts_
Actual: 
![screen shot 2016-06-23 at 2 12 39 pm](https://cloud.githubusercontent.com/assets/1447148/16316525/9597d760-394c-11e6-9a86-992ee976658c.png)

**Comment by johnzeringue** [comment]
Not that this means there isn't any connection, but the issue I observed was Gradle independent of IntelliJ.

**Comment by nanodeath** [comment]
I also expected to be able to configure *just* a subproject (for now) as a `*.gradle.kts` file, while leaving the root project as a regular Groovy script, but I've yet to figure out how to make that work. I'm basically seeing what @mkobit screenshotted. I'll keep fiddling with my settings.gradle file for now.

**Comment by bamboo** [comment]
Fixed by #37.
