### ISSUE TITLE
IDEA restart is required after project import

### ISSUE THREAD

**Issue by cbeams** [gradle/gradle-script-kotlin#82]
## Environment

 - Gradle 3.0 M2 (which includes Gradle Script Kotlin 0.2.0)
 - IDEA 2016.1.2
 - Kotlin IDEA plugin 1.1.0-dev-1222

## Steps to reproduce

 1. Follow the instructions in the [0.2.0 samples README](https://github.com/gradle/gradle-script-kotlin/tree/v0.2.0/samples#readme), and be sure especially to install version 1.1.0-dev-1222 of the Kotlin IDEA plugin.
 1. At the step titled [Import the sample project into IDEA](https://github.com/gradle/gradle-script-kotlin/tree/v0.2.0/samples#import-the-sample-project-into-idea), open `build.gradle.kts` and notice that the project does **not** import cleanly as advertised. Notice that `build.gradle.kts` has many errors due to "unresolved references"

![image](https://cloud.githubusercontent.com/assets/301810/16303262/9d1b294e-3904-11e6-9aa2-ddac5aafd710.png)

## Workaround

 1. After importing the project and seeing the errors, `File->Invalidate Caches/Restart` then click `Just Restart`
 2. Notice that after IDEA finishes restarting, `build.gradle.kts` is error-free, and everything else works as expected per the samples README.

**Comment by yole** [comment]
Looks like this is exactly what Pavel Talanov fixed in this build of the plugin: https://teamcity.jetbrains.com/viewLog.html?buildId=805470&buildTypeId=bt345&tab=artifacts

**Comment by cbeams** [comment]
@yole, it is the same issue. I'm just adding the issue for tracking purposes. Going to resolve it immediately with an update to the samples README that points to the new dev build.
